// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCli1_Isq3jfr31HCYsz_qJxJEl1NNQ9h4',
    appId: '1:270790876602:android:b01fcac64349781bc31183',
    messagingSenderId: '270790876602',
    projectId: 'treinopro-c0ee5',
    storageBucket: 'treinopro-c0ee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfc1faXT6YzsdAQLNEmZSnuK9wOX6LSpA',
    appId: '1:270790876602:ios:5edc29f15a155802c31183',
    messagingSenderId: '270790876602',
    projectId: 'treinopro-c0ee5',
    storageBucket: 'treinopro-c0ee5.firebasestorage.app',
    iosBundleId: 'com.treinopro.oficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfc1faXT6YzsdAQLNEmZSnuK9wOX6LSpA',
    appId: '1:270790876602:ios:840b54dc3100445bc31183',
    messagingSenderId: '270790876602',
    projectId: 'treinopro-c0ee5',
    storageBucket: 'treinopro-c0ee5.firebasestorage.app',
    iosBundleId: 'com.example.treinoproApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN6Mh2Qshcumo1NvKNffNiKMc9X4vn0EQ',
    appId: '1:270790876602:web:1e5dd412bd763291c31183',
    messagingSenderId: '270790876602',
    projectId: 'treinopro-c0ee5',
    authDomain: 'treinopro-c0ee5.firebaseapp.com',
    storageBucket: 'treinopro-c0ee5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN6Mh2Qshcumo1NvKNffNiKMc9X4vn0EQ',
    appId: '1:270790876602:web:e9eb6a99e5ad11b4c31183',
    messagingSenderId: '270790876602',
    projectId: 'treinopro-c0ee5',
    authDomain: 'treinopro-c0ee5.firebaseapp.com',
    storageBucket: 'treinopro-c0ee5.firebasestorage.app',
  );

}